name: th_scheduler
description: "Scheduler application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: #^1.0.6
  shared_preferences: #^2.0.15
  intl: #dateFormatter
  provider: #multiProvider for different login type
  firebase_core:
  firebase_auth:
  firebase_auth_web:
  cloud_firestore:
  firebase_database:
  country_picker: #^2.0.18 #Phone Number Country Picker
  twilio_flutter: #^0.3.0
  pinput: #^2.2.16 #OTP Widget
  fluttertoast: #^8.0.9 #UI helper (error show)
  qr_flutter: #QR Parser
  barcode_scan2: #QR Scanner
  path_provider: #^2.0.11 # Save image
  image_gallery_saver: #^1.7.1 # Save image

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

  #   fonts:
  #     - family: Schyler
  #       fonts:
  #         - asset: fonts/Schyler-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700