// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4YEhscoMK4xgtcfJo2thFGnpfvNploJ4',
    appId: '1:463945083186:web:34512eb8d7072853174f2b',
    messagingSenderId: '463945083186',
    projectId: 'th-scheduler-89eaa',
    authDomain: 'th-scheduler-89eaa.firebaseapp.com',
    storageBucket: 'th-scheduler-89eaa.appspot.com',
    measurementId: 'G-18PVB1NE03',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCvRztY-GCL25w1o1D0bH5Lq6g8PxJZLsM',
      appId: '1:463945083186:android:2ea44cb4266e8b21174f2b',
      messagingSenderId: '463945083186',
      projectId: 'th-scheduler-89eaa',
      storageBucket: 'th-scheduler-89eaa.appspot.com',
      androidClientId:
          '463945083186-8ss7ofjiridq413vec7ufjek8t95n6kf.apps.googleusercontent.com');
}
